### PR TITLE
Fix version update 1.62.1

### PR DESCRIPTION
**Pull request by m-rossi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

It seems as if #22 was not complete. A version update was missing.

### CODE REVIEW

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
@isuruf why are two versions defined there? Could we not use https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds for the pre-releases?

**Comment by isuruf** [comment]
1.63.0 is a stable version now.

**Comment by m-rossi** [comment]
@isuruf May we do separate PRs for both version updates? Otherwise this seems ready to merge.

**Comment by jakirkham** [comment]
Thoughts @conda-forge/rust-activation?

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
