### PR TITLE
Update stable Rust to 1.74

### LINKED ISSUE #39: Update to Rust 1.74
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The Rust cross-target toolchains are currently at 1.73, while Rust has released version 1.74. Updates of Deno are blocked until the 1.74 Rust packages are available.

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

### PR DESCRIPTION
**Pull request by mdekstrand**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #39.

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by mdekstrand** [comment]
@xhochy do it seems to be failing on a subset of Mac cross-builds, do we need to do anything there?

**Comment by xhochy** [comment]
I hope to fix this in https://github.com/conda-forge/rust-activation-feedstock/pull/42

**Comment by xhochy** [comment]
Fixed by #42

**Pull request closed without merging**
