### PR TITLE
rust 1.75.0

### PR DESCRIPTION
**Pull request by pavelzw**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pavelzw** [comment]
@conda-forge/rust-activation this is ready for review.

**Comment by xhochy** [comment]
@h-vetinari I would value your insight on this PR. This changes the minimal OSX version for rust to 10.12. Do you know how to correctly handle this?

**Comment by h-vetinari** [comment]
The CBC looks alright, you just need:
```
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx and x86_64]
```
under `run:` (or `run_constrained:`), so that the outputs themselves have the correct metadata as well.

**Comment by h-vetinari** [comment]
Ah, I hadn't gotten the detail that this is also about binaries produced by rust >=1.75. Thanks Isuru. :)

**Comment by xhochy** [comment]
> Ah, I hadn't gotten the detail that this is also about binaries produced by rust >=1.75. Thanks Isuru. :)

Yes, that's why I was hesitant to merge here.

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Pull request merged**
