### PR TITLE
Bump main to `1.81.0`, dev to `1.83.0`

### PR DESCRIPTION
**Pull request by mbrobbel**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mbrobbel** [comment]
@conda-forge-admin, please rerender

**Comment by mbrobbel** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please restart ci

**Comment by mbrobbel** [comment]
@conda-forge-admin please restart ci

**Comment by xhochy** [comment]
We're running into https://github.com/conda-forge/cctools-and-ld64-feedstock/issues/79

**Pull request merged**
