### PR TITLE
Update main to 1.63.0 and dev to 1.65.0

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
This is failing as `rust_dev` is not part of the channel sources. Should this be re-added?

**Comment by charlesbluca** [comment]
I think so, IIUC it was removed in https://github.com/conda-forge/rust-activation-feedstock/pull/23/commits/fc33737420a51df8606c71d4fe404c1c677ebac7 so that 1.62.1 and 1.63.0 could both be released on `main` with https://github.com/conda-forge/rust-activation-feedstock/pull/23

cc @isuruf

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by xhochy** [comment]
Thanks @isuruf

**Pull request merged**
